name: Deploy

on:
  push:
    branches:
    - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: deploy
        run: |
          tar -a -c -f LambdaBackend.zip .github controllers helpers routes .env .gitignore conn.js form-body.js lambda.js package.json package-lock.json request.rest server.js node_modules